name: signify_test
description: "Quote App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^3.0.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio_cache_interceptor: ^3.5.0
  get_it: ^7.6.7
  share_plus: ^7.2.2
  rating_bar_updated: ^0.2.0
  go_router: ^13.1.0
  flutter_native_splash: ^2.3.10
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  icon_background_color_dark: "#000000"
  image: assets/images/logo.png
  android_12:
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/logo.png"
    min_sdk_android: 21
    web:
      generate: true
      image_path: "assets/images/logo.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/images/logo.png"
      icon_size: 48
    macos:
      generate: true
      image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald-Regular.ttf